services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

  influxdb:
    image: influxdb:latest
    #ports:
    #  - '8086:8086'
    #volumes:
    #  - influxdb-var-data:/var/lib/influxdb2
    #  - ./influxdb/testdata:/testdata
    #  - ./influxdb/restore_testdata.sh:/docker-entrypoint-initdb.d/restore_testdata.sh
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}

  nginx:
    image: nginx:alpine
    ports:
      - '3001:80'
    volumes:
      - ./data:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

